### ISSUE TITLE
SignalRChat (OWIN version) is incorrect

### ISSUE THREAD

**Issue by MrPbody** [MicrosoftDocs/feedback#1266]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/tutorial-getting-started-with-signalr

**Problem:**
The app creation instructions produce a non-functional app. The instructions were followed precisely twice and failed both times. The jquery version available at the time was 3.3.1, and the jquery.signalR version 2.2.2. 

When the app is run with IE11 it fails with the message "Unhandled exception at line 2, column 31040 in http://localhost:26263/Scripts/jquery-3.3.1.min.js
0x800a138f - JavaScript runtime error: Unable to get property 'client' of undefined or null reference"

When run with Firefox 65.0.2 the JS console reports: "jQuery.Deferred exception: chat is undefined @http://localhost:26263/index.html:34:13
l@http://localhost:26263/Scripts/jquery-3.3.1.min.js:2:29373
a/</c<@http://localhost:26263/Scripts/jquery-3.3.1.min.js:2:29677
undefined"

When run in Chrome 72.0.3626.109 the message is "jQuery.Deferred exception: Cannot read property 'client' of undefined TypeError: Cannot read property 'client' of undefined
    at HTMLDocument.<anonymous> (http://localhost:26263/index.html:34:18)
    at l (http://localhost:26263/Scripts/jquery-3.3.1.min.js:2:29375)
    at c (http://localhost:26263/Scripts/jquery-3.3.1.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2
jquery-3.3.1.min.js:2 Uncaught TypeError: Cannot read property 'client' of undefined
    at HTMLDocument.<anonymous> (index.html:34)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)"

**Comment by MrPbody** [comment]
The solution is to add this line to Startup.cs:

app.MapSignalR();
