### ISSUE TITLE
Exception missing from list of errors for `Directory.EnumerateFiles()`

### ISSUE THREAD

**Issue by pressacco** [MicrosoftDocs/feedback#1361]
Context:
- Related Article: [Directory.EnumerateFiles Method](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles?view=netframework-4.7#System_IO_Directory_EnumerateFiles_System_String_)
- Problem: An error is missing from the list of exceptions.

The `EnumerateFiles()` method can also throw the following:
```
System.IO.IOException: The process cannot access the file 'C:\Directory\PathHere' because it is being used by another process.
```

This exception is thrown by:

```
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileSystemEnumerableIterator`1.CommonInit()
at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
at System.IO.Directory.EnumerateFiles(String path)
```

----

**ON A RELATED NOTE**

The "Feedback" [form](https://github.com/MicrosoftDocs/feedback/issues/new?template=Custom.md) that is used to submit this issue states that:

**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

For some reason, [this](https://github.com/MicrosoftDocs/feedback/issues/new?template=Custom.md) MSDN page does not have:
- a comments section
- a "Was this helpful?" link

Additional Context:
- I was logged into the MSDN, and 
- I have refreshed the page to ensure that this was not a caching issue

**Comment by ryanmajidi** [comment]
@rloutlaw Can you take a look at this issue?

**Comment by rloutlaw** [comment]
@pressacco IOException is listed on the page you linked:

 " IOException
path is a file name."

**Comment by pressacco** [comment]
@rloutlaw  Yes `IOException` is listed. 
- Unfortunately the sample error 
   - > path is a filename
- is very different from what I experienced: 
   - > The process cannot access the file 'C:\Directory\PathHere' because it is being used by another process.

It might be worth mentioning in the documentation... or not.
