### ISSUE TITLE
Download the contents of a DriveItem use msgraph sdk

### ISSUE THREAD

**Issue by yuanlincong** [MicrosoftDocs/feedback#3497]
**Describe the bug**
i want to download content use msgraph sdk,
this is my code:

 SimpleAuthProvider authProvider = new SimpleAuthProvider("token");
        IGraphServiceClient buildClient = GraphServiceClient.builder().authenticationProvider(authProvider)
                .buildClient();
        IDriveItemCollectionPage iDriveItemCollectionPage = buildClient.me()
                .drives("driveId").items("itemId").children().buildRequest().get();
        List<DriveItem> currentPage = iDriveItemCollectionPage.getCurrentPage();
        for (DriveItem driveItem : currentPage) {
            System.out.println(driveItem.id + " ===== " + driveItem.name + " ===== " + driveItem.file);
            if (null != driveItem.file) {
                // get file inputstream,throw exception
                InputStream inputStream = buildClient.drives("driveId").items(driveItem.id).content().buildRequest()
                        .get();
                System.out.println(inputStream);
                inputStream.close(); 
            }
        }
when i get inputstream,throw exception.
exception detail is :
SEVERE: CoreHttpProvider[send] - 204Error during http request
Feb 19, 2021 6:01:42 AM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
com.microsoft.graph.core.ClientException: Error during http request
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:422)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
        at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:306)
        at com.microsoft.graph.http.CustomRequest.get(CustomRequest.java:43)
        at com.canto.dmc.repository.manager.Migrate202010Caption.process(Migrate202010Caption.java:52)
        at com.canto.dmc.repository.util.ContextProcessorHelper.initializer(ContextProcessorHelper.java:65)
        at com.canto.dmc.repository.manager.Migrate202010Caption.main(Migrate202010Caption.java:27)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: Check failed.
        at okhttp3.internal.connection.Transmitter.prepareToConnect(Transmitter.kt:124)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.microsoft.graph.httpcore.RedirectHandler.intercept(RedirectHandler.java:123)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.microsoft.graph.httpcore.RetryHandler.intercept(RetryHandler.java:140)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:31)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:356)
        ... 15 more

**Comment by yuanlincong** [comment]
ok,i upgrade sdk version to 2.8.1,this problem has resolved,
thanks

**Comment by rootsmusic** [comment]
#please-close
