### ISSUE TITLE
How to fix it??

### ISSUE THREAD

**Issue by behrad1234** [MicrosoftDocs/feedback#3634]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/instahack/hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "/data/data/com.termux/files/home/instahack/hackinsta.py", line 114, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'

**Comment by rootsmusic** [comment]
@behrad1234 Please provide more details, including where's the doc.
