### ISSUE TITLE
Active Directory Replication Status Tool broken

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/feedback#3823]
**Describe the bug**
downloading the latest version here https://www.microsoft.com/en-us/download/details.aspx?id=30005 installs fine but when trying to run it reports "This version of the tool has expired"

**To Reproduce**
Go here, download, install it on domain controller and try to run it.
https://www.microsoft.com/en-us/download/details.aspx?id=30005

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37478978/177649749-5dc7323e-9daf-4180-a67e-eb84dafc12c0.png)

**Desktop (please complete the following information):**
 - OS: Server 2016

**Smartphone (please complete the following information):**

**Additional context**

**Comment by red-erik** [comment]
Hello,
do you have any update ? This tool is a MUST for a lot of people so why not to stop let it expiring ?
Thank you.
Regards,
Red.

**Comment by Taomyn** [comment]
Really would like to have a working version of this tool to get some information on our domain.

**Comment by TonyClements** [comment]
I would also really like a working version to get info from our domain

**Comment by JtotheR** [comment]
I know this has previously been stated by others.  This is a great tool and we would really like to have a working version of this tool.  Hopefully with some work around application licensing that auto renews so we don't have this problem again in a few years.

**Comment by rdegennaro** [comment]
This is the tool that Microsoft points to for troubleshooting replication issues and downloaded on their site.  It is crazy that it is released in an unusable state for new servers.

**Comment by Alpha-Soft-GmbH** [comment]
Hello MS, 
This tool is a MUST for a lot of people so why not to stop let it expiring ?
Thank you.

**Comment by jleathlean** [comment]
I also concur - this is the 3rd/4th time the tool has expired, but the first time they haven't replaced it before the expiration. :(

There are a lot of us who use this tool on a regular basis - and I'm not aware of any other tools that work in the same manner.

**Comment by rdegennaro** [comment]
I searched and could not find anything that did the same thing.  I tried command line tools to find out what objects were conflicting.  I got no results, even though the tools also said replication was broken.

Warning, what I'm about to link to might not be for you!  _Please do your own due diligence._  Once I flipped this [regkey](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc816938(v=ws.10)?redirectedfrom=MSDN), after the next sync, I saw account objects that were conflicting.  There was the account from the FSMO server (I think).  And additional accounts from our remote sites with SIDs tacked on the end.  

I waited a few days to make sure everything settled down.  Then a bit of cleanup in removing & adding users/computers and it looks good.  I'm waiting a few more days for things to settle down further.  Then I'll flip the regkey back.  And hope no more conflicts come up that prevent replication.  The regkey should not be left in "loose" mode.  I remember reading that even putting it into "loose" mode was not recommended.

**Comment by MrTroyH** [comment]
This tool is extremely handy, please don't set it to expire.  Thank you.

**Comment by mark-royds** [comment]
Another frustrated admin here.  Why did this even have a time-limited license in the first place?

**Comment by barbarajoost** [comment]
Have the same problem. There are meanwhile lots of threads around concerning this. I don't understand why nobody at Microsoft seems to be interested in this problem. They insult their customers with ignorance.

**Comment by hadox** [comment]
Please fix. I need it for a AD Domain migration

**Comment by tinakane** [comment]
I would also like a fix for this as we use it in my company as well.

**Comment by chmura-werdna** [comment]
Is Microsoft going to grace us with any sort of acknowledgement that a tool that most AD administrators use to check their domain health or is this just going to sit in limbo?

**Comment by RussEfarmer** [comment]
This is an important tool for our environment and I would very much like it to be usable again.

**Comment by benmprojects** [comment]
@microsoftopensource Any Update?

**Comment by ra-ataka** [comment]
Same here, awaiting Microsoft comments

**Comment by jackvadan** [comment]
Hello, is there any other way to view repliation status of multi forest and child server environment.

**Comment by ii-batman** [comment]
Hi Everyone, 
**While we wait for a new tool to be released, do you know of a good powershell script that does the same?**
Thanks M

**Comment by janweis** [comment]
Please deploy a new license for us @microsoft

Thanks,
Jan

**Comment by rangaraj73** [comment]
@microsoft ,

 Could you solve the issue of AD Replication status tool license getting expired.

**Comment by mitlyng** [comment]
There is a new published date of 7/18/2022 in the download link, testing.
Thank you for fixing but please remove the expiration.

**Comment by mitlyng** [comment]
The new adreplstatusInstaller.msi version lacks a digital certificate so Edge will declare it unsafe. When attempting to install Windows will also give the pop up stating it is unsafe.

**Comment by chmura-werdna** [comment]
> Hi Everyone, **While we wait for a new tool to be released, do you know of a good powershell script that does the same?** Thanks M

@ii-batman You could always run the old `repadmin /showrepl` and `repadmin /replsummary` in command line, as well as the `dcdiag` commands.

To add on @mitlyng 's comment - the newly published MSI file still does not work - I removed the previously installed replication status tool and installed the one release on 7/18/2022 and get the same result with the license expiration warning. 

@microsoft - this has been an issue for 2 weeks, with the amount of money you charge for server licensing and CALs, there is no reason your customers should be experiencing this issue on a tool many admins use regularly coupled with a total lack of response on your end.

**Comment by ii-batman** [comment]
Hi Everyone, 

I have used the latest version fine, just needs .net 4.8 and I was able to check my DC's with the tool without any issues.

Thanks for the community effort to get up and running again.

**Comment by awstew1** [comment]
I installed .net 4.8, rebooted, still same error.

**Comment by mitlyng** [comment]
@chmura-werdna, Can confirm it works on on Windows 10 ENT, 11 ENT, and Server 2016 to 2022.

**Comment by awstew1** [comment]
have installed it on win10 ent, server 2016 & server 2019 - all running .net 4.8, no luck

**Comment by barbarajoost** [comment]
The next time bomb is already implemented. This time the license is only valid until April 15, 2023. This is less than one year. How stupid are this people at Microsoft? What the heck have they planned for this tool?

**Comment by Taomyn** [comment]
I must be looking at a different download link to everyone else because although the date on the site is 18/07/2022 the version downloaded is still the same one from last year.

I've reclicked the one in the OP on several machines and caches cleared etc.

**Comment by awstew1** [comment]
This worked for me

https://www.microsoft.com/en-us/download/details.aspx?id=30005

**Comment by barbarajoost** [comment]
Klick on the download page on "details". There must be the date 7/18/2022. Otherwise you 

> I must be looking at a different download link to everyone else because although the date on the site is 18/07/2022 the version downloaded is still the same one from last year.
> 
> I've reclicked the one in the OP on several machines and caches cleared etc.

Klick on the download page on "details". Under "date published" must be the date 7/18/2022. Otherwise you have a wrong link.

**Comment by barbarajoost** [comment]
The tool is broken again. This time it looks like a problem with .NET. On Windows 10 the start screen appears wirh "initializing" and then - nothing. No event in the eventlog.  On Server 2019 the following errors will be logged:

Faulting application name: repl.exe, version: 3.22.415.100, time stamp: 0x62593e89
Faulting module name: KERNELBASE.dll, version: 10.0.17763.3287, time stamp: 0x2637e772
Exception code: 0xe0434352
Fault offset: 0x0000000000039319
Faulting process id: 0x2920
Faulting application start time: 0x01d8cc4a39655838
Faulting application path: C:\Program Files (x86)\Microsoft Active Directory Replication Status Tool\repl.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 505793d3-dee9-45ec-9927-f5d01f148683
Faulting package full name: 
Faulting package-relative application ID: 
------------------------------------------------------------------------------------------------
Application: repl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Sirona.PackagingException
   at Microsoft.Sirona.Packaging.PackageHelper.ValidatePackage(System.IO.Stream, System.String, Boolean, Boolean)
   at Microsoft.Sirona.Packaging.PackageManager.LoadInternal(System.IO.Stream, Boolean, Boolean, System.String, System.String, Boolean)
   at Microsoft.Sirona.Packaging.PackageManager.Load(System.String, Boolean, Boolean)

Exception Info: Microsoft.Sirona.PackagingException
   at Microsoft.Sirona.Packaging.PackageManager.Load(System.String, Boolean, Boolean)
   at repl.MainWindow.LoadConfiguration(Microsoft.Sirona.Configuration.ConfigurationManager)
   at repl.MainWindow.SetupSironaComponents()
   at repl.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at repl.App.Main()

**Comment by coppolaf** [comment]
Guys, 
same here!!

my trace is excatly as barbarajoost reported...
exacttly same errors.... 
here running on 2012 R2 servers (6 DCs none actually working)
if i check replication manually with repadmin /showrepl and repadmin /replsummary
it fortunately reports no errors but... 
checking that with a GUI is simple to analyze than read a long text file!

news??
waiting....

**Comment by mbanks850** [comment]
> The tool is broken again. This time it looks like a problem with .NET. On Windows 10 the start screen appears wirh "initializing" and then - nothing. No event in the eventlog. On Server 2019 the following errors will be logged:
> 
> Faulting application name: repl.exe, version: 3.22.415.100, time stamp: 0x62593e89 Faulting module name: KERNELBASE.dll, version: 10.0.17763.3287, time stamp: 0x2637e772 Exception code: 0xe0434352 Fault offset: 0x0000000000039319 Faulting process id: 0x2920 Faulting application start time: 0x01d8cc4a39655838 Faulting application path: C:\Program Files (x86)\Microsoft Active Directory Replication Status Tool\repl.exe Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll Report Id: 505793d3-dee9-45ec-9927-f5d01f148683 Faulting package full name: Faulting package-relative application ID:
> 
> Application: repl.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: Microsoft.Sirona.PackagingException at Microsoft.Sirona.Packaging.PackageHelper.ValidatePackage(System.IO.Stream, System.String, Boolean, Boolean) at Microsoft.Sirona.Packaging.PackageManager.LoadInternal(System.IO.Stream, Boolean, Boolean, System.String, System.String, Boolean) at Microsoft.Sirona.Packaging.PackageManager.Load(System.String, Boolean, Boolean)
> 
> Exception Info: Microsoft.Sirona.PackagingException at Microsoft.Sirona.Packaging.PackageManager.Load(System.String, Boolean, Boolean) at repl.MainWindow.LoadConfiguration(Microsoft.Sirona.Configuration.ConfigurationManager) at repl.MainWindow.SetupSironaComponents() at repl.MainWindow..ctor()
> 
> Exception Info: System.Windows.Markup.XamlParseException at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri) at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri) at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean) at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext) at System.Windows.Application.DoStartup() at System.Windows.Application.<.ctor>b__1_0(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef) at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame) at System.Windows.Application.RunDispatcher(System.Object) at System.Windows.Application.RunInternal(System.Windows.Window) at repl.App.Main()

I am seeing this same error on a 2019 DC.

**Comment by barbarajoost** [comment]
Thanks to @MrTroyH ! And to the guy who shared his edited version of the dll on spiceworks. I'm not a programmer or developer. I looked in this tool dnSpy like a pig in a clockwork. But the shared file works.

**Comment by ra-ataka** [comment]
Cheers @MrTroyH brilliant contribution

**Comment by bene-tleilax-werdna** [comment]
While I can appreciate the ingenuity of the community for the suggested work-around, whatever happened to the idea that when you pay a company like Microsoft to use their products, there's a reasonable expectation the software company acknowledge and fix said issues when their customers report them? This is an issue reported by a number of system administrators for business customers who continue to be ignored by @microsoft - who has neither acknowledged the latest issue with the tool, nor attempted to fix it in any meaningful way. Nor have they addressed the fact that the license (why is there a license to use this tool?) expires on April 15, 2023.

**Comment by barbarajoost** [comment]
Seems the October patches broke the tool again.

**Comment by aneymann** [comment]
Hello
I found a solution working well for https://www.reddit.com/r/sysadmin/comments/xpfune/ad_replication_status_tool_broken_again_in_early/

**Comment by schittli** [comment]
> 

Most *Customer* related M$ "Services" like feedback, docs, and UserVoice, is just one thing: a big shame. user feedback is getting ignored for years (google for the next Outlook-Error you'll get and you'll note that the Bug is well known for many years and if you look further, you'll find the information that the bug was reported by customers many times during all those years).

There is just one workaround:
1. Setup Hybrid cloud, e.g. Azure & AWS or Google, which is anyway a great idea to not get locked in
2. For each User SW, always evaluate alternatives. For example, we have just rolled out Cisco Webex for our 750 employees to replace M$ Teams

If enough customers do this, then M$$ will soon get back to being Customer friendly. I know, this probably never happens. Why should they, if they earn billions every quarter?

**Comment by gauravelearn** [comment]
> The solution is to edit the Microsoft.Sirona.dll file as noted by the awesome "Brandhor" in this Reddit post: https://www.reddit.com/r/sysadmin/comments/xpfune/ad_replication_status_tool_broken_again_in_early/ Posted what my dll looks like here(troyheiss): https://community.spiceworks.com/topic/2462722-active-directory-replication-status-tool-broken

Thank you very much. It's very useful.

**Comment by cjramseyer** [comment]
It's a shame that a company like Microsoft provides a tool that has a certificate that has already expired.
The certificate expired September 1, 2022.

The suggested fix above, has resolvd the issue

**Comment by barbarajoost** [comment]
We can now await the next time the tool will no longer work.
![adreptool-error](https://user-images.githubusercontent.com/38276477/227912322-7252617f-bd5d-4891-9dfa-71c00e0e65aa.jpg)

**Comment by ecoidan** [comment]
Hello Microsoft!!!  Are you there???  Again your tool has expired.  Please get the new verison out there. please!

**Comment by cjramseyer** [comment]
It has been expired for a while.  Microsoft is not focused on AD anymore, 
even though it will be around for a long time.
There is a published fix for it.  You have to replace a dll and modify one 
file and it will work agai

**Comment by barbarajoost** [comment]
Or you change to the new tool by Ryan Ries. See the link above provided by MrTroyH. It looks basic but it works fine and gives all information you need.

**Comment by MrTroyH** [comment]
I see that new tool, but I haven’t tried it successfully yet.  My work
laptop has a lot of software restrictions.

Not as next, next, finish as MS AD Replication Tool.

**Comment by dc8554** [comment]
I was able to get the tool to launch by changing the system time back a year to 2022. 

Ran it on a test VM, stopped the windows time service and used the PowerShell `set-date` cmdlet. Surprisingly, it seems to work and can read from ADDS with the system time being off.

**Comment by MrTroyH** [comment]
Ryan Ries created an ADReplStatus that I switched too and I like it:  GitHub
- ryanries/ADReplStatus: AD Replication Status Tool
<https://github.com/ryanries/adreplstatus>
Look on the right-side under "Releases," click on it and that'll take you
to a zip you can download named "ADReplStatus_v1.2.1.zip"

**Comment by dlxpbva** [comment]
+1, tool still does not work.

**Comment by ksl28** [comment]
+1, Its still broken. Please fix it Microsoft!

**Comment by ii-batman** [comment]
+1 still no download! 
Also why is there a a KB: [https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/get-use-active-directory-replication-status-tool](url) still active when there is no way to get it?

**Comment by red-erik** [comment]
MS Crap...switch to Ryan Ries tool (still to be enhanced) but working. MS is "abandoning" ADDS to live it's support only to parthners, while focusing on Azure Ad only
