### ISSUE TITLE
 Scaffold movie pages not work 

### ISSUE THREAD

**Issue by kasemsun** [MicrosoftDocs/feedback#3910]
**Describe the bug**
When I follow the document Add MVC Controller with views, using Entity Framework. it return me an error

Finding the generator 'controller'...
Running the generator 'controller'...
No database provider found. Using 'SqlServer' by default for new DbContext creation!
Minimal hosting scenario!
Generating a new DbContext class 'MyFirstMVC.Data.MyFirstMVCContext'
startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

**To Reproduce**
follow the document Part 4, add a model to an ASP.NET Core MVC app

**Screenshots**
![image](https://user-images.githubusercontent.com/61727392/230018167-5353fc16-0ac6-4586-a5ae-325d331463cb.png)
![image](https://user-images.githubusercontent.com/61727392/230018473-5dac4d7c-476f-453d-bcfb-90512be8d19a.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser chrome
 - Version 22H2

**Additional context**

**Comment by Rick-Anderson** [comment]
@gewarren  how can we close this issue? https://github.com/MicrosoftDocs/feedback/issues has become a bit bucket.
